{-
http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
-}

euler002 :: Integer
euler002 = sum (filter even (takeWhile (< 4000000) [fib(x) | x <- [1..]]))

main = putStrLn (show euler002)

fib :: Integer -> Integer
fib 0 = 0
fib 1 = 1
fib 2 = 2
fib n = fib(n-1) + fib(n-2)
